# fly.toml app configuration file generated for pooling on 2025-06-19T13:37:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pooling'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

# Define separate processes for the web server and the training worker
[processes]
  web = "gunicorn --bind [::]:5001 --workers 1 --threads 2 --preload train_integrated:app"
  worker = "python -u train_integrated.py --run-training"
